#!/usr/bin/expect
set username [lindex $argv 0]
set password [lindex $argv 1]
set hostnumber [lindex $argv 2]

log_user 0

if {[llength $argv] < 3} {
	send_user "Usage: cse-login-simulator username password hostnumber\n"
	exit 1
}


spawn ssh -t ${username}@cse-p204inst${hostnumber}.cse.psu.edu "bash -l"

set timeout 10

set connected 0

while {$connected == 0} {
	expect {
		"yes/no" {
			send "yes\r"
		}
		"password:" {
			send "$password\r"
			send_user "Please use DUO mobile app to confirm login...\n"
			set connected 1
		}
		"Connection refused" {
			send_user "Connection refused. Automatically activating Cisco AnyConnect VPN...\n"
			spawn /opt/cisco/anyconnect/bin/vpn
			set timeout 10
			expect {
				"VPN>" {
					send "connect vpn.its.psu.edu\r"
				}
				eof {
					send_user "any connect not detected. Login failed.\n"
					exit
				}
			}
			expect "Group" {send "0\r" }
			expect "Username" {send "$username\r" }
			expect "Password" {send "$password\r"}
			expect "accept" {send "y\r"}
			expect "VPN>" {send "exit\r"}
			send_user "VPN activated, tring to reconnect..\n"
			spawn ssh -t ${username}@cse-p204inst${hostnumber}.cse.psu.edu "bash -l"
		}
		timeout {
			send_user "Time out. Please try again.\n"
			exit 1
		}

		"Could not resolve hostname" {
			send_user "Could not resolve hostname. Please try again.\n"
			exit 1
		}

		eof {
			send_user "Unexpected error occured. Please try again\n"
			exit 1
		}
	}
}

set timeout 5
expect "Passcode or option (1-3):" {send "1\r"}

set timeout 60
expect {
	"cse" {
		send "stty erase \\^?\r"
	}
	timeout {
		send_user "Don't Forget to confirm on DUO mobile app.. Please try again"
	}
}

log_user 1
interact
